### PR TITLE
fixed input validator issues

### PR DESCRIPTION
**Pull request by adityar224**
Fixed Input Validator issues where null wasn't returned when the if condition used in the validator wasn't true. Replaced this with the ternery operator throughout the project.

Have also added a missing validation statement in the sign in page.

### CODE REVIEW

**Comment by anoochit** [comment]
@adityar224  I have changed the sign-in screen and sign-up screen using a Flutter UI instated.

**Comment by adityar224** [comment]
Hey I've remerged with your changes too

**Comment by anoochit** [comment]
> 

Hi, I have a lot of change on the project. now I have migrate some path to use GetX to replace Beamer for navigator2 and fix TextFieldTag in add device dialog BUT it's still bug in validation this field must required value. so can you fix #8  ?

**Comment by adityar224** [comment]
Ok I'll look into it

**Pull request closed without merging**
